version: "3"
services:
  ui:
    container_name: easy-movie-ui
    image: "registry.cn-shenzhen.aliyuncs.com/xinze517/easy-movie-ui:${COMMIT:-commit}"
    ports:
      - "23000:80"
    networks:
      - easy-movie-net

networks:
  easy-movie-net:
    external: true